apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8081"
  db_host: "mysql-docker:3306"
  database: "msvc_usuarios"
  username: "root"
  password: "sasa"
  curso_url: "msvc-cursos:8082"
  application.yaml: |-
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente desarrollo
    ---
      spring:
        config:
          activate:
            on-profile: prod
      config:
        texto: Configurando ambiente desarrollo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8082"
  db_host: "postgres-docker:5432"
  database: "msvc_cursos"
  username: "postgres"
  password: "sasa"
  curso_url: "msvc-usuarios:8081"



