apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-docker
  name: postgres-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-docker
  template:
    metadata:
      labels:
        app: postgres-docker
    spec:
      containers:
      - name: postgres-docker
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: sasa
          - name: POSTGRES_DB
            value: msvc_cursos
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data-postgres
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
