apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: nwoswo/amigoscode-customer:2.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "800m"
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: postgres-config
