services:

  ############
  #POSTGRES
  ############
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa
      PGDATA: /data/postgres
    volumes:
      - data-postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  ############
  #PGADMIN
  ############
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nwoswo@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-sasa}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin4:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  ############
  #ZIPKIN
  ############
  # zipkin:
  #   image: openzipkin/zipkin
  #   container_name: zipkin
  #   ports:
  #     - 9411:9411
  #   networks:
  #     - spring

  # ############
  # #RABBITMQ
  # ############
  # rabbitmq:
  #   image: rabbitmq:3.8.11-management
  #   container_name: rabbitmq
  #   volumes:
  #     - data-rabbit:/var/lib/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - spring
  ############
  #MICRO SERVICES
  ############
  # customer:
  #   image: amigoscode-customer:2.0-SNAPSHOT
  #   container_name: customer
  #   ports:
  #     - "8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring
  #     - postgres
  #   depends_on:
  #     - zipkin
  #     - postgres
  #     - rabbitmq


  # fraud:
  #   image: amigoscode-fraud:2.0-SNAPSHOT
  #   container_name: fraud
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring
  #     - postgres
  #   depends_on:
  #     - zipkin
  #     - postgres
  #     - rabbitmq


  # notification:
  #   image: amigoscode-notification:2.0-SNAPSHOT
  #   container_name: notification
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring
  #     - postgres
  #   depends_on:
  #     - zipkin
  #     - postgres
  #     - rabbitmq

networks:
  postgres:
    driver: bridge
  # spring:
  #   driver: bridge

volumes:
  data-postgres:
    name: data-postgres
  data-pgadmin4:
    name: data-pgadmin4
  # data-rabbit:
  #   name: data-rabbit